#
# Esto de momento no utiliza Emscripten y sinceramente si puedo evitarlo, lo haré.
#
wasm:
	clang-12 \
		--target=wasm32 \
		-emit-llvm \
		-c \
		-S \
		src/wasm/imagedata.c \
		src/div.c \
		src/palette.c \
		src/framebuf.c \
		src/interpol.c \
		src/point.c \
		src/rect.c \
		src/game.c \
		src/actor.c
	llc-12 \
		-march=wasm32 \
		-filetype=obj \
		wasm.ll
	wasm-ld-12 \
		--no-entry \
		--export-all \
		-o wasm.wasm \
		wasm.o
